function Hd = FIRfilter
%FIRFILTER Returns a discrete-time filter object - (for polyphase
%filtering)

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 07-Sep-2016 21:13:55

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

N     = 624;  % Order
Fpass = 0.5;  % Passband Frequency
Fstop = 0.7;  % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 5;    % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
